USE BUDT703_Project_0507_13
--SQL DROP TABLES:

DROP TABLE IF EXISTS [PPP.Play];
DROP TABLE IF EXISTS [PPP.Opponent];
DROP TABLE IF EXISTS [PPP.Match];
DROP TABLE IF EXISTS [PPP.Location];
DROP TABLE IF EXISTS [PPP.Date];


--SQL CREATE TABLES:

CREATE TABLE [PPP.Date] (
	datMch DATE NOT NULL,
	datDay CHAR (3) NOT NULL,
	CONSTRAINT pk_Date_datMch PRIMARY KEY (datMch))


CREATE TABLE [PPP.Location] (
	locId CHAR(5) NOT NULL,
	locCty VARCHAR (20),
	locState VARCHAR (5),
	CONSTRAINT pk_Location_locId PRIMARY KEY (locId))


CREATE TABLE [PPP.Match] (
	mchId CHAR(10) NOT NULL,
	mchAt VARCHAR (10),
	mchScrUmd INT,
	mchScrOpp INT,
	locId CHAR(5) NOT NULL,
	CONSTRAINT pk_Match_mchId PRIMARY KEY (mchId),
	CONSTRAINT fk_Match_locId FOREIGN KEY (locId)
		REFERENCES [PPP.Location] (locId)
		ON DELETE CASCADE ON UPDATE CASCADE)


CREATE TABLE [PPP.Opponent] (
	oppId CHAR(5) NOT NULL,
	oppName VARCHAR(20),
	CONSTRAINT pk_Opponent_oppId PRIMARY KEY (oppId))


CREATE TABLE [PPP.Play] (
	mchId CHAR(10) NOT NULL,
	datMch DATE NOT NULL,
	oppId CHAR(5) NOT NULL
CONSTRAINT pk_Play_mchId_datMch_oppId PRIMARY KEY (mchId,datMch,oppId),
CONSTRAINT fk_Play_mchId FOREIGN KEY (mchId)
		REFERENCES [PPP.Match] (mchId)
		ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_Play_datMch FOREIGN KEY (datMch)
		REFERENCES [PPP.Date] (datMch)
		ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_Play_oppId FOREIGN KEY (oppId)
		REFERENCES [PPP.Opponent] (oppId)
		ON DELETE CASCADE ON UPDATE CASCADE)
